---

- clean: [ '~' ]

- link:
    # Vim
    ~/.vimrc: vimrc
    ~/.vim: vim/

    # Bash
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.bash_prompt: bash_prompt
    ~/.aliases: aliases
    ~/.exports: exports
    ~/.functions: functions
    ~/.paths: paths

    # Config
    ~/.config/terminator: config/terminator/

    # Fonts
    ~/.local/share/fonts: fonts/

    # Miscellaneous
    ~/.tmux.conf: tmux.conf
